eWAY gateway: Update docs. Require address.
Docs:

* Remove old copy & paste about TrustCommerce.
* Add info about transaction results.
* Add test credit card number, provided by eway docs
  (http://www.eway.com.au/developers/sandbox/direct-payments.html)

Code:

* :order_id is not a required parameter, so remove it
* Add :address and :billing_address to required parameters, because if
  you don't pass address to gateway, you'll get:

    Error: Required XML tag(s) missing, or incorrect case used. Required tag Name(s): ewayCustomerAddress, ewayCustomerPostcode

* Remove tests for invalid expiration date and verification value.
  Seems like the Test eWay Gateway doesn't care about the validity of
  them and always returns a success code.

Closes #378.